### ISSUE TITLE
convert_multi_params can't deal with floats

### ISSUE THREAD

**Issue by aaron-parsons** [DiamondLightSource/Savu#155]
If I put a range of center of rotations into the process list ie:
"55.0;55.2;55.4;55.6;55.8;56.0;56.2;56.4;56.6;56.8;57.0"
 I get:
ValueError: invalid literal for int() with base 10: '55.0'
    self.set_parameters(params)
  File "/home/clb02321/DAWN_stable/Savu/savu/plugins/plugin.py", line 105, in set_parameters
    value = self.convert_multi_params(parameters[key], key)
  File "/home/clb02321/DAWN_stable/Savu/savu/plugins/plugin.py", line 118, in convert_multi_params
    value = map(dtype, value)
ValueError: invalid literal for int() with base 10: '55.0'

Astra can take sub pixels as the centre of rotation so it would be nice to have this functionality

**Comment by nicwade** [comment]
The centre of rotation is set to be an integer, which is why it doesn't support floats.  The Astra algorithms currently used require that the sinogram passed in is already centered.  This requires padding the data, so the smallest unit is an integer.  So even if you passed in a float, it would convert to an integer. 

There is a different way of specifying the geometry, which I'm implementing for the 3D case, which allows a centre value to be passed in (so I assume this supports float).  This geometry is specifically 3D, but I will test to see if we can get it to work for 2D, where the extra dimension has length one.  

I did test convert_multi_params for floats and it works fine (as long as the parameter is a float).
