### ISSUE TITLE
Integrate all standard tomography loaders

### ISSUE THREAD

**Issue by nicwade** [DiamondLightSource/Savu#222]

**Comment by nicwade** [comment]
This will include 3D, 3D to 4D and 4D data, with or without image key, and a possibility to add separate darks and flats.

**Comment by nicwade** [comment]
Related to #223

**Comment by rcatwood** [comment]
Some things to keep in mind for a unified loader:
-- Flats (possibly darks) may also have different exposure time from the radiographic projections and this information will need to be known for some analysis methods
-- There may be flats before, intermediate flats,  and flats after and the ability for subsequent plugins to 'know' which ones are which should not be neglected (though we haven't used this on I12 due to the monochromator characteristics )
-- the ability to extend integration time by acquiring multiple exposures for each projection is under development , I think this would best be handled by making it an extra dimension  and later choosing the (plugin) method to combine the data (average, dezing-average, motion correction first ...? )

**Comment by nicwade** [comment]
Initial integration completed and will be available in the next release.

Regarding the 3 points above:
(1) There is now an optional scale value you can pass for both darks and flats
(2) This is available via the image key
(3) I'll raise a separate ticket for this.  This is something that will be added in when we have some example data.
