### ISSUE TITLE
Astra breaking for diffraction tomography?

### ISSUE THREAD

**Issue by aaron-parsons** [DiamondLightSource/Savu#308]
Exception: The dimensions of the data do not match those specified in the geometry.

When running i22 tomo test (cpu or gpu).

It could be just me, I haven't written a loader in a while, although it works fine with the pass through test.

**Comment by nicwade** [comment]
This should be fixed in version 1 now (but not on module load savu yet as I need to check it passes tests first).  The next error is due to the Q meta data entry not being available when outputting the meta data.

At first glance, the hdf5 dataset is already closed, and this seems to occur when the input dataset is closed.  So most likely it is not copied correctly.

**Comment by aaron-parsons** [comment]
Isn't this the identical use case as for the I18 diffraction tomography? Same meta-data and everything.

How come one worked and passed the tests and the other didnt?


________________________________

**Comment by nicwade** [comment]
The data was flipped in this instance.  Astra expects the sinogram to be ordered as (rot_angle, detX), but it was the other way around and padding was being applied to the wrong dimension.  I've updated so it can be either way now. 

Regarding the meta_data, it shouldn't contain links to hdf5 datasets as they cannot be copied, but the data should be read in so it is a numpy array.  Once the original data object is deleted the file will be closed and not accessible for any other data objects.  I wonder if this is causing the problem with Steve's pipeline (since it doesn't exist when copying of metadata is deleted). 

I can't test it because your recent push broke things.

**Comment by aaron-parsons** [comment]
OK, fixed my tests, but in build 885 the stats test starts to fail. This was where you changed the sinogram in astra. Not sure why that would cause this to fail though since it is completely unrelated.
