### ISSUE TITLE
dawn_compatible decorator is not compatible with savu_config

### ISSUE THREAD

**Issue by nicwade** [DiamondLightSource/Savu#384]
The configurator cannot import e.g. Paganin, but if you remove the dawn_compatible decorator it seems fine.

**Comment by nicwade** [comment]
I've had to remove the dawn_compatible decorators from pymca and paganin to get the configurator to work

**Comment by aaron-parsons** [comment]
It was, but someone has changed line 
p = load_plugin(dawn_plugins[plugin]['path2plugin'])#.strip('.py'))

If you uncomment the strip then it will work

**Comment by srikanthnagella** [comment]
That was me. i didn't test it in linux. It didn't work in windows as load
needed full filename.

**Comment by nicwade** [comment]
Tried it but it didn't fix the problem I'm afraid.

**Comment by aaron-parsons** [comment]
Hmm. OK. Resolve it to make the configurator work and I’ll look at a later date.

**Comment by aaron-parsons** [comment]
So this is fixed and merged into master. The problem was that '.py' needed to be split from the path. Not sure if this affects windows @srikanthnagella?

Anyways, I've now added a test for the configurator, and for dawn_compatible. They needed to be run in a separate instance of python from the rest of the tests, and are located in the scripts package.

Re-open this ticket if there are issues, but I'll close it for now.
